# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bridge_pb2 as bridge__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAgentTurn = channel.unary_stream(
                '/atomos.bridge.AgentService/StreamAgentTurn',
                request_serializer=bridge__pb2.AgentRequest.SerializeToString,
                response_deserializer=bridge__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.StoreSecret = channel.unary_unary(
                '/atomos.bridge.AgentService/StoreSecret',
                request_serializer=bridge__pb2.StoreSecretRequest.SerializeToString,
                response_deserializer=bridge__pb2.StoreSecretResponse.FromString,
                _registered_method=True)
        self.HasSecret = channel.unary_unary(
                '/atomos.bridge.AgentService/HasSecret',
                request_serializer=bridge__pb2.HasSecretRequest.SerializeToString,
                response_deserializer=bridge__pb2.HasSecretResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamAgentTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAgentTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAgentTurn,
                    request_deserializer=bridge__pb2.AgentRequest.FromString,
                    response_serializer=bridge__pb2.AgentResponse.SerializeToString,
            ),
            'StoreSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSecret,
                    request_deserializer=bridge__pb2.StoreSecretRequest.FromString,
                    response_serializer=bridge__pb2.StoreSecretResponse.SerializeToString,
            ),
            'HasSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.HasSecret,
                    request_deserializer=bridge__pb2.HasSecretRequest.FromString,
                    response_serializer=bridge__pb2.HasSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atomos.bridge.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atomos.bridge.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAgentTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/atomos.bridge.AgentService/StreamAgentTurn',
            bridge__pb2.AgentRequest.SerializeToString,
            bridge__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atomos.bridge.AgentService/StoreSecret',
            bridge__pb2.StoreSecretRequest.SerializeToString,
            bridge__pb2.StoreSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atomos.bridge.AgentService/HasSecret',
            bridge__pb2.HasSecretRequest.SerializeToString,
            bridge__pb2.HasSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
