# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\ratomos.bridge\"N\n\x0c\x41gentRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06images\x18\x03 \x03(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x03(\x04\"Q\n\rAgentResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\x11\n\ttool_call\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t2^\n\x0c\x41gentService\x12N\n\x0fStreamAgentTurn\x12\x1b.atomos.bridge.AgentRequest\x1a\x1c.atomos.bridge.AgentResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREQUEST']._serialized_start=31
  _globals['_AGENTREQUEST']._serialized_end=109
  _globals['_AGENTRESPONSE']._serialized_start=111
  _globals['_AGENTRESPONSE']._serialized_end=192
  _globals['_AGENTSERVICE']._serialized_start=194
  _globals['_AGENTSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
