#!/bin/bash
# Ensure pmbootstrap is available natively. On a real Linux host (e.g.
# Multipass VM) this is required because the 'install' step creates loop
# device partitions (/dev/loopXp1) that do not work inside Docker containers.
#
# Resolution order:
#   1. `pmbootstrap` already on PATH                           -> use it
#   2. iso-postmarketos/vendor/pmbootstrap/pmbootstrap.py      -> wrap it (PREFERRED)
#   3. pip3 / pipx install of upstream pmbootstrap              -> last resort
#
# Vendoring rationale: AtomOS pins a known-good pmbootstrap snapshot under
# vendor/pmbootstrap so build hosts do not depend on the live PyPI release
# and so the FP4 install path remains reproducible across hosts. When the
# vendor tree is present we install a tiny shim at ~/.local/bin/pmbootstrap
# that just execs the vendored pmbootstrap.py with the host's python3.
# That keeps pmbootstrap a normal `pmbootstrap ...` command for everything
# else in scripts/pmb/, scripts/build-image.sh, etc.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VENDOR_PMB_DIR="$ROOT_DIR/vendor/pmbootstrap"
VENDOR_PMB_ENTRY="$VENDOR_PMB_DIR/pmbootstrap.py"
USER_BIN="$HOME/.local/bin"
SHIM_PATH="$USER_BIN/pmbootstrap"
SHIM_MARKER="# AtomOS shim: forwards every pmbootstrap invocation to the vendored copy"

# Detect whether an existing PATH entry is OUR shim (in which case it is
# already pointing at the vendored copy and we trust it) vs an unrelated
# pip-installed / system pmbootstrap (which we want to shadow with the
# vendored shim so behavior stays reproducible).
existing_pmb_is_our_shim() {
    local existing
    existing="$(command -v pmbootstrap 2>/dev/null || true)"
    [ -n "$existing" ] || return 1
    [ -f "$existing" ] || return 1
    grep -q "AtomOS shim" "$existing" 2>/dev/null
}

install_vendor_shim() {
    local entry="$1"
    if ! command -v python3 >/dev/null 2>&1; then
        echo "ERROR: python3 is required to use the vendored pmbootstrap." >&2
        return 1
    fi
    mkdir -p "$USER_BIN"
    cat > "$SHIM_PATH" <<EOF
#!/bin/sh
# AtomOS shim: forwards every pmbootstrap invocation to the vendored copy
# at iso-postmarketos/vendor/pmbootstrap/. Pinned to that exact tree so
# upstream PyPI releases cannot drift the install behavior under us.
# Regenerated by scripts/pmb/ensure-pmbootstrap.sh.
exec python3 "$entry" "\$@"
EOF
    chmod 0755 "$SHIM_PATH"
    echo "ensure-pmbootstrap: installed vendored shim: $SHIM_PATH -> $entry"
    case ":$PATH:" in
        *":$USER_BIN:"*)
            ;;
        *)
            echo "WARN: $USER_BIN is not in PATH; add it (e.g. via ~/.profile or ~/.bashrc) so pmbootstrap is reachable." >&2
            ;;
    esac
}

# --- Fast path: shim already installed, vendor entry still exists ---------
if existing_pmb_is_our_shim && [ -f "$VENDOR_PMB_ENTRY" ]; then
    # Already wired up from a previous run; trust it.
    exit 0
fi

# --- Path 2: vendored pmbootstrap (preferred) -----------------------------
if [ -f "$VENDOR_PMB_ENTRY" ]; then
    if install_vendor_shim "$VENDOR_PMB_ENTRY"; then
        export PATH="$USER_BIN:$PATH"
        if PMB_VER="$(pmbootstrap --version 2>&1 | head -1)"; then
            echo "pmbootstrap (vendored): $PMB_VER"
            exit 0
        fi
        echo "WARN: vendored pmbootstrap shim installed but --version failed; will try pip fallback." >&2
    fi
fi

# --- Already-installed (non-shim) pmbootstrap -----------------------------
# If pip / pipx / system put pmbootstrap on PATH and the vendor copy is not
# usable, accept the existing one rather than reinstalling.
if [ ! -f "$VENDOR_PMB_ENTRY" ] && command -v pmbootstrap >/dev/null 2>&1; then
    echo "pmbootstrap (existing on PATH, vendor copy not present): $(command -v pmbootstrap)"
    exit 0
fi

# --- Path 3: pip install fallback -----------------------------------------
echo "pmbootstrap not found and vendored copy unavailable / unusable - installing via pip..."

if ! command -v pip3 >/dev/null 2>&1 && ! command -v pipx >/dev/null 2>&1; then
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3-pip python3-venv >/dev/null
    elif command -v apk >/dev/null 2>&1; then
        sudo apk add --no-interactive --quiet py3-pip
    else
        echo "ERROR: Cannot install pip3. Install pmbootstrap manually:" >&2
        echo "  pip3 install --user pmbootstrap" >&2
        exit 1
    fi
fi

if command -v pipx >/dev/null 2>&1; then
    pipx install pmbootstrap
elif pip3 install --user --break-system-packages pmbootstrap 2>/dev/null; then
    true
elif pip3 install --user pmbootstrap 2>/dev/null; then
    true
else
    echo "ERROR: pip3 install failed. Trying with venv..." >&2
    python3 -m venv /tmp/.pmb-venv
    /tmp/.pmb-venv/bin/pip install pmbootstrap
    sudo ln -sf /tmp/.pmb-venv/bin/pmbootstrap /usr/local/bin/pmbootstrap
fi

PMB_PATH="$(command -v pmbootstrap 2>/dev/null || true)"
if [ -z "$PMB_PATH" ] && [ -x "$USER_BIN/pmbootstrap" ]; then
    export PATH="$USER_BIN:$PATH"
    PMB_PATH="$USER_BIN/pmbootstrap"
fi
if [ -z "$PMB_PATH" ]; then
    echo "ERROR: pmbootstrap installed but not in PATH." >&2
    echo "  Add ~/.local/bin to your PATH and retry." >&2
    exit 1
fi

echo "pmbootstrap installed: $PMB_PATH ($(pmbootstrap --version 2>&1 || true))"
