#!/bin/bash
# build-fairphone4.sh — pmbootstrap-free Fairphone 4 image builder.
#
# Same model as scripts/build-qemu.sh: bootstrap an aarch64 rootfs into a
# docker/podman volume, install Alpine + postmarketOS APKs directly via
# `apk --root /target add`, build the AtomOS Rust + custom phosh
# components in a heavy container, install AtomOS overlays directly, and
# emit fastboot-flashable artifacts (boot.img + sparse fairphone-fp4.img)
# under build/host-export-fairphone-fp4/.
#
# What changed from build-image.sh:
#   - No pmbootstrap. Everything happens via Alpine + docker/podman the
#     same way build-qemu.sh works for the QEMU profile.
#   - postmarketOS APKs (device-fairphone-fp4, firmware-fairphone-fp4-*,
#     linux-postmarketos-qcom-sm6350, hexagonrpcd, mkbootimg,
#     make-dynpart-mappings, soc-qcom*, postmarketos-base) come from
#     the official pmOS mirror at https://mirror.postmarketos.org/...
#     The pmOS signing key is vendored at
#     pmaports/main/postmarketos-keys/build.postmarketos.org.rsa.pub.
#   - boot.img is generated by `mkbootimg` using the offsets/pagesize
#     from pmaports/device/community/device-fairphone-fp4/deviceinfo
#     (DTB appended to kernel because deviceinfo_append_dtb="true").
#   - Rootfs is packed into a sparse ext4 image suitable for
#     `fastboot flash userdata fairphone-fp4.img` (or super-partition
#     payload, depending on device-side workflow).
#
# Usage:
#   bash scripts/build-fairphone4.sh [profile-env] \
#       [--without-overview-chat-ui] [--without-home-bg]
#
# Output:
#   build/host-export-fairphone-fp4/boot.img
#   build/host-export-fairphone-fp4/fairphone-fp4.img
#
# Environment overrides:
#   ATOMOS_FP4_ALPINE_CONTAINER_IMAGE   base image (default alpine:edge)
#   ATOMOS_FP4_PMOS_CHANNEL             pmOS channel/branch (default master)
#   ATOMOS_FP4_PMOS_MIRROR              pmOS mirror URL
#                                       (default https://mirror.postmarketos.org/postmarketos/)
#   ATOMOS_FP4_MESON_CACHE_HOST_DIR     host bind mount for /cache (else
#                                       named docker volume)
#   ATOMOS_FP4_MESON_CACHE_CLEAN=1      wipe meson/ccache cache
#   ATOMOS_FP4_BUILD_ENGINE             docker | podman (auto-detected)
#   ATOMOS_FP4_ROOTFS_SIZE_MB           pack target for fairphone-fp4.img
#                                       (default: rootfs size + 256 MiB)
#   ATOMOS_FP4_KEEP_ROOTFS_VOLUME=1     do not remove the rootfs volume
#                                       on exit (debug)
set -euo pipefail

usage() {
    cat >&2 <<'EOF'
Usage: build-fairphone4.sh [profile-env] [--without-overview-chat-ui] [--without-home-bg] [--without-app-switcher]

Builds a fastboot-flashable Fairphone 4 image (boot.img + fairphone-fp4.img)
from Alpine Linux + the postmarketOS APK mirror, without pmbootstrap.

Options:
  --without-overview-chat-ui    Skip building/installing atomos-overview-chat-ui.
  --without-home-bg             Skip building/installing atomos-home-bg.
  --without-app-switcher        Skip building/installing atomos-app-handler.
                                Legacy --without-swipe-bridge accepted (alias).

Outputs:
  build/host-export-fairphone-fp4/boot.img
  build/host-export-fairphone-fp4/fairphone-fp4.img
EOF
}

PROFILE_ENV=""
BUILD_OVERVIEW_CHAT_UI=1
BUILD_HOME_BG=1
BUILD_APP_HANDLER=1
while [ "$#" -gt 0 ]; do
    case "$1" in
        --without-overview-chat-ui|--skip-overview-chat-ui)
            BUILD_OVERVIEW_CHAT_UI=0
            ;;
        --without-home-bg|--skip-home-bg)
            BUILD_HOME_BG=0
            ;;
        --without-app-switcher|--skip-app-switcher|--without-swipe-bridge|--skip-swipe-bridge)
            BUILD_APP_HANDLER=0
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "ERROR: unknown option: $1" >&2
            usage
            exit 1
            ;;
        *)
            if [ -n "$PROFILE_ENV" ]; then
                echo "ERROR: profile env provided more than once: $1" >&2
                usage
                exit 1
            fi
            PROFILE_ENV="$1"
            ;;
    esac
    shift
done
PROFILE_ENV="${PROFILE_ENV:-config/fairphone-fp4.env}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Shared host-side helpers (atomos_find_container_engine, atomos_require_tools,
# atomos_cleanup_volume). build-qemu.sh sources the same file -- single source
# of truth for the small bits of host orchestration both targets need.
# shellcheck source=scripts/_lib-build-common.sh
source "$ROOT_DIR/scripts/_lib-build-common.sh"

PROFILE_ENV_SOURCE="$PROFILE_ENV"
if [ ! -f "$PROFILE_ENV_SOURCE" ] && [ -f "$ROOT_DIR/$PROFILE_ENV" ]; then
    PROFILE_ENV_SOURCE="$ROOT_DIR/$PROFILE_ENV"
fi
if [ ! -f "$PROFILE_ENV_SOURCE" ]; then
    echo "ERROR: missing profile env: $PROFILE_ENV" >&2
    exit 2
fi
# shellcheck source=/dev/null
source "$PROFILE_ENV_SOURCE"

if [ -z "${PROFILE_NAME:-}" ]; then
    echo "ERROR: PROFILE_NAME missing in $PROFILE_ENV_SOURCE" >&2
    exit 2
fi
if [ "${PMOS_DEVICE:-}" != "fairphone-fp4" ]; then
    echo "ERROR: PMOS_DEVICE='${PMOS_DEVICE:-}' (expected 'fairphone-fp4')." >&2
    echo "  This script is only for the Fairphone 4 profile. Use scripts/build-qemu.sh for QEMU." >&2
    exit 2
fi

if [ "$(uname -s)" != "Linux" ]; then
    echo "ERROR: build-fairphone4.sh requires a Linux host (loop devices + privileged container)." >&2
    exit 2
fi

REPO_TOP="$(cd "$ROOT_DIR/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build"
EXPORT_DIR="$BUILD_DIR/host-export-${PROFILE_NAME}"
WORK_DIR="$BUILD_DIR/fairphone4-${PROFILE_NAME}"
BOOT_IMG_PATH="$EXPORT_DIR/boot.img"
ROOTFS_IMG_PATH="$EXPORT_DIR/${PROFILE_NAME}.img"
ALPINE_IMAGE="${ATOMOS_FP4_ALPINE_CONTAINER_IMAGE:-alpine:edge}"
PMOS_CHANNEL="${ATOMOS_FP4_PMOS_CHANNEL:-master}"
PMOS_MIRROR="${ATOMOS_FP4_PMOS_MIRROR:-https://mirror.postmarketos.org/postmarketos/}"
INSTALL_PASSWORD="${PMOS_INSTALL_PASSWORD:-147147}"
PMOS_USER_UID="${PMOS_USER_UID:-10000}"
HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

ROOTFS_VOLUME="atomos-fp4-rootfs-${PROFILE_NAME}"
MESON_CACHE_VOLUME="atomos-fp4-meson-cache-${PROFILE_NAME}"
MESON_CACHE_HOST_DIR="${ATOMOS_FP4_MESON_CACHE_HOST_DIR:-}"
PMOS_KEY_HOST="$ROOT_DIR/pmaports/main/postmarketos-keys/build.postmarketos.org.rsa.pub"
DEVICEINFO_HOST="$ROOT_DIR/pmaports/device/community/device-fairphone-fp4/deviceinfo"

if [ ! -f "$PMOS_KEY_HOST" ]; then
    echo "ERROR: missing postmarketOS signing key: $PMOS_KEY_HOST" >&2
    echo "  Restore from upstream pmaports (main/postmarketos-keys/) and retry." >&2
    exit 2
fi
if [ ! -f "$DEVICEINFO_HOST" ]; then
    echo "ERROR: missing FP4 deviceinfo: $DEVICEINFO_HOST" >&2
    exit 2
fi

# Pull boot.img layout out of the vendored deviceinfo so we don't drift
# from upstream. All values are sourced as deviceinfo_* shell vars.
# shellcheck source=/dev/null
(
    set +u
    source "$DEVICEINFO_HOST"
    : "${deviceinfo_dtb:?missing deviceinfo_dtb}"
    : "${deviceinfo_arch:?missing deviceinfo_arch}"
)
# shellcheck source=/dev/null
source "$DEVICEINFO_HOST"
DEVICE_DTB="${deviceinfo_dtb}"
DEVICE_ARCH="${deviceinfo_arch:-aarch64}"
DEVICE_APPEND_DTB="${deviceinfo_append_dtb:-false}"
DEVICE_PAGESIZE="${deviceinfo_flash_pagesize:-4096}"
DEVICE_BASE="${deviceinfo_flash_offset_base:-0x00000000}"
DEVICE_KOFF="${deviceinfo_flash_offset_kernel:-0x00008000}"
DEVICE_ROFF="${deviceinfo_flash_offset_ramdisk:-0x01000000}"
DEVICE_SOFF="${deviceinfo_flash_offset_second:-0x00000000}"
DEVICE_TOFF="${deviceinfo_flash_offset_tags:-0x00000100}"
DEVICE_FLASH_SPARSE="${deviceinfo_flash_sparse:-true}"
DEVICE_KERNEL_CMDLINE="${deviceinfo_kernel_cmdline:-PMOS_NO_OUTPUT_REDIRECT}"
unset deviceinfo_dtb deviceinfo_arch deviceinfo_append_dtb deviceinfo_format_version 2>/dev/null || true
unset deviceinfo_flash_pagesize deviceinfo_flash_offset_base deviceinfo_flash_offset_kernel \
      deviceinfo_flash_offset_ramdisk deviceinfo_flash_offset_second deviceinfo_flash_offset_tags \
      deviceinfo_flash_sparse deviceinfo_kernel_cmdline 2>/dev/null || true

if [ "$DEVICE_ARCH" != "aarch64" ]; then
    echo "ERROR: unsupported deviceinfo_arch '$DEVICE_ARCH' (expected aarch64)." >&2
    exit 2
fi

# Re-source profile env (the deviceinfo source above clobbered some vars
# and we need PMOS_EXTRA_PACKAGES / PMOS_PARITY_PACKAGE_CANDIDATES for the
# package manifest below).
# shellcheck source=/dev/null
source "$PROFILE_ENV_SOURCE"

atomos_require_tools
ENGINE="${ATOMOS_FP4_BUILD_ENGINE:-$(atomos_find_container_engine)}"
if [ -z "$ENGINE" ]; then
    echo "ERROR: docker or podman is required for FP4 image build." >&2
    exit 2
fi

mkdir -p "$EXPORT_DIR" "$WORK_DIR"

# Repos file: Alpine edge {main, community, testing} + postmarketOS edge.
# pmbootstrap channels.cfg maps the "edge" channel to branch_pmaports=main,
# so the pmOS repo URL we want is <mirror>/main (NOT <mirror>/master,
# despite the channel id; see iso-postmarketos/pmaports/.ci/dint.sh and
# iso-postmarketos/pmaports/channels.cfg).
PMOS_REPO_URL="${PMOS_MIRROR%/}/main"
case "$PMOS_CHANNEL" in
    master|main|edge) : ;;
    *) PMOS_REPO_URL="${PMOS_MIRROR%/}/${PMOS_CHANNEL}" ;;
esac
REPOSITORIES_FILE="$WORK_DIR/etc_apk_repositories"
cat > "$REPOSITORIES_FILE" <<EOF
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
$PMOS_REPO_URL
EOF

# Meson incremental cache (same as build-qemu.sh; named docker volume by
# default for macOS bind-mount EPERM resilience even though build-qemu
# already requires Linux — keeps the option open).
if [ -n "$MESON_CACHE_HOST_DIR" ]; then
    MESON_CACHE_MOUNT="$MESON_CACHE_HOST_DIR"
    MESON_CACHE_KIND="host directory: $MESON_CACHE_HOST_DIR"
    mkdir -p "$MESON_CACHE_HOST_DIR"
else
    MESON_CACHE_MOUNT="$MESON_CACHE_VOLUME"
    MESON_CACHE_KIND="docker volume: $MESON_CACHE_VOLUME"
    "$ENGINE" volume create "$MESON_CACHE_VOLUME" >/dev/null
fi
if [ "${ATOMOS_FP4_MESON_CACHE_CLEAN:-0}" = "1" ]; then
    echo "build-fairphone4: ATOMOS_FP4_MESON_CACHE_CLEAN=1 -> wiping cache ($MESON_CACHE_KIND)"
    if [ -n "$MESON_CACHE_HOST_DIR" ] && [ -d "$MESON_CACHE_HOST_DIR" ]; then
        "$ENGINE" run --rm -v "$MESON_CACHE_HOST_DIR:/cache" \
            "$ALPINE_IMAGE" /bin/sh -c 'rm -rf /cache/* /cache/.[!.]* 2>/dev/null || true' \
            >/dev/null 2>&1 || rm -rf "$MESON_CACHE_HOST_DIR"
        mkdir -p "$MESON_CACHE_HOST_DIR"
    elif [ -z "$MESON_CACHE_HOST_DIR" ]; then
        "$ENGINE" volume rm -f "$MESON_CACHE_VOLUME" >/dev/null 2>&1 || true
        "$ENGINE" volume create "$MESON_CACHE_VOLUME" >/dev/null
    fi
fi
echo "build-fairphone4: meson cache backend: $MESON_CACHE_KIND"

cleanup_volume() {
    # FP4-specific keep-volume opt-out (lets `make build-fairphone4` reuse a
    # bootstrapped Alpine arm64 rootfs across iterations -- saves ~3 min of
    # apk install on each rebuild). The actual volume removal is delegated
    # to atomos_cleanup_volume() in scripts/_lib-build-common.sh; this
    # wrapper just adds the gate.
    if [ "${ATOMOS_FP4_KEEP_ROOTFS_VOLUME:-0}" = "1" ]; then
        echo "build-fairphone4: keeping rootfs volume $ROOTFS_VOLUME (ATOMOS_FP4_KEEP_ROOTFS_VOLUME=1)"
        return 0
    fi
    atomos_cleanup_volume "$ENGINE" "$ROOTFS_VOLUME"
}
trap cleanup_volume EXIT
cleanup_volume
"$ENGINE" volume create "$ROOTFS_VOLUME" >/dev/null

##############################################################################
# Step 1: bootstrap Alpine + pmOS rootfs into the docker volume.
##############################################################################
echo "=== build-fairphone4: bootstrap Alpine + pmOS rootfs (arch=$DEVICE_ARCH) ==="

# Same approach as build-qemu's BASE_APK_PACKAGES, but tuned for the FP4
# device profile. Keep parity with build-qemu's GNOME / portal / dev set
# wherever it makes sense; the device-fairphone-fp4 dep set will pull the
# kernel + firmware + Qualcomm SoC userspace transitively.
BASE_APK_PACKAGES=(
    # Alpine base + OpenRC plumbing.
    alpine-base
    busybox-openrc
    openrc
    dbus
    dbus-openrc
    bash
    shadow
    util-linux
    util-linux-openrc
    # losetup is its own apk on Alpine edge (NOT pulled by util-linux
    # metapackage). postmarketos-mkinitfs hook 00-initramfs-base.files
    # references /usr/sbin/losetup, so the binary must exist in the
    # rootfs or initramfs generation fails. We also create a /usr/sbin
    # symlink in the post-bootstrap fixup step because Alpine still
    # installs losetup to /sbin/losetup while pmOS hooks expect /usr/sbin.
    losetup
    util-linux-misc
    # boot-deploy (pmOS tool that assembles boot.img after mkinitfs)
    # uses GNU bc syntax (multi-character variable names like
    # `available`) and GNU df options (`--output=avail`). The busybox
    # provided variants reject both:
    #   bc: POSIX only allows one character names; this is bad: 'vailable*0.9'
    #   df: /tmp/mkinitfs<pid>: can't find mount point
    # Install GNU coreutils + bc explicitly so /usr/bin/bc and
    # /usr/bin/df shadow busybox in the chroot's PATH.
    coreutils
    bc
    # boot-deploy is pulled in transitively by postmarketos-base /
    # postmarketos-mkinitfs already, but list it explicitly so the
    # bootstrap manifest is self-documenting.
    boot-deploy
    e2fsprogs
    dosfstools
    openssh
    openssh-server-pam
    sudo
    doas
    haveged
    haveged-openrc
    chrony
    chrony-openrc
    nftables
    nftables-openrc
    eudev
    eudev-openrc
    elogind
    elogind-openrc
    sleep-inhibitor
    sleep-inhibitor-openrc
    openrc-settingsd
    openrc-settingsd-openrc
    polkit-elogind
    seatd
    seatd-openrc
    zram-init
    zram-init-openrc
    networkmanager
    networkmanager-openrc
    modemmanager
    modemmanager-openrc
    wpa_supplicant
    wpa_supplicant-openrc
    bluez
    bluez-openrc
    pipewire
    pipewire-pulse
    wireplumber
    dconf
    # XDG portals + GNOME core that pmOS pulls via base-ui-gnome.
    gnome-session
    gnome-settings-daemon
    gnome-control-center
    gnome-shell-schemas
    gnome-bluetooth
    gnome-keyring
    xwayland
    adwaita-icon-theme
    xdg-desktop-portal-gtk
    xdg-desktop-portal-wlr
    xdg-desktop-portal-phosh
    xdg-user-dirs
    xdg-user-dirs-gtk
    udiskie
    dnsmasq
    gcr-ssh-agent
    glycin-loaders-all
    glycin-thumbnailer
    gnome-backgrounds
    gst-thumbnailers
    iio-sensor-proxy
    iio-sensor-proxy-openrc
    power-profiles-daemon
    apk-polkit-rs-openrc
    # Phosh stack (the FP4 default UI).
    phoc
    phoc-schemas
    phosh
    phosh-schemas
    phosh-mobile-settings
    phosh-wallpapers
    feedbackd
    squeekboard
    simdutf
    greetd
    greetd-openrc
    greetd-phrog
    # AtomOS overlay runtime libs (also pulled by *-dev below; explicit
    # for parity with build-qemu so the rootfs always carries them even
    # when the home-bg helper falls back to container-only build).
    webkit2gtk-6.0
    gtk4-layer-shell
    # Dev tooling for on-device cargo build / debug (mirrors
    # PMOS_EXTRA_PACKAGES from config/fairphone-fp4.env).
    build-base
    binutils
    gdb
    cargo
    rust
    pkgconf
    ripgrep
    glib-dev
    gdk-pixbuf-dev
    pango-dev
    cairo-dev
    gtk4.0-dev
    libadwaita-dev
    gtk4-layer-shell-dev
    graphene-dev
    gsettings-desktop-schemas
    # postmarketos-base-ui-gnome _pmb_recommends app set (parity with QEMU).
    decibels
    g4music
    gnome-calculator
    gnome-calendar
    gnome-clocks
    gnome-console
    gnome-contacts
    gnome-maps
    gnome-software
    gnome-software-plugin-apk2
    gnome-text-editor
    gnome-user-share
    gnome-weather
    gvfs-full
    nautilus
    papers
    showtime
    snapshot
    firefox-esr
    flatpak
    fprintd
    loupe
)

# postmarketOS-only packages (no Alpine equivalent): pulled from the pmOS
# mirror. device-fairphone-fp4 transitively pulls firmware-fairphone-fp4-*
# / linux-postmarketos-qcom-sm6350 / hexagonrpcd / make-dynpart-mappings /
# mkbootimg / soc-qcom* / postmarketos-base.
PMOS_APK_PACKAGES=(
    postmarketos-base
    postmarketos-base-ui
    postmarketos-base-ui-gnome
    postmarketos-base-ui-gnome-mobile
    postmarketos-ui-phosh
    device-fairphone-fp4
    # mkbootimg-osm0sis is the variant pmOS ships and uses for FP4.
    mkbootimg-osm0sis
    make-dynpart-mappings
    # postmarketos-mkinitfs is responsible for assembling the initramfs
    # cpio archive from the kernel modules + udev rules + hooks. The
    # device-fairphone-fp4 package pulls it transitively via
    # postmarketos-base, but list it explicitly so the manifest is
    # self-documenting.
    postmarketos-mkinitfs
    postmarketos-initramfs
    # android-tools provides img2simg for sparse image conversion of the
    # final fairphone-fp4.img.
    android-tools
)

# Profile extras + parity candidates (same merging logic as build-qemu).
PROFILE_EXTRA_CSV="${PMOS_EXTRA_PACKAGES:-}"
PARITY_CSV="${PMOS_PARITY_PACKAGE_CANDIDATES:-}"

PACKAGE_MANIFEST="$(
    python3 - "$PROFILE_EXTRA_CSV" "$PARITY_CSV" "${BASE_APK_PACKAGES[*]}" "${PMOS_APK_PACKAGES[*]}" <<'PY'
import sys

profile = [p.strip() for p in sys.argv[1].split(",") if p.strip()]
parity = [p.strip() for p in sys.argv[2].split(",") if p.strip()]
base = [p.strip() for p in sys.argv[3].split() if p.strip()]
pmos = [p.strip() for p in sys.argv[4].split() if p.strip()]

# Map a few legacy names that creep in from older configs.
replacements = {
    "webkit6.0-gtk4-dev": "webkit2gtk-6.0-dev",
}
ordered = []
for group in (base, pmos, profile, parity):
    for p in group:
        p = replacements.get(p, p)
        if not p:
            continue
        if p not in ordered:
            ordered.append(p)
print(" ".join(ordered))
PY
)"

echo "Effective APK package set:"
echo "  $PACKAGE_MANIFEST"

"$ENGINE" run --rm --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target" \
    -v "$REPOSITORIES_FILE:/tmp/repositories:ro" \
    -v "$PMOS_KEY_HOST:/tmp/pmos.rsa.pub:ro" \
    "$ALPINE_IMAGE" /bin/sh -eu -c "
        mkdir -p /target/etc/apk/keys
        cp -r /etc/apk/keys/. /target/etc/apk/keys/
        # Trust the postmarketOS signing key in BOTH the host apk DB (so
        # apk --root /target add can verify pmOS index signatures during
        # bootstrap) AND in the target rootfs (so on-device apk continues
        # to trust the same mirror).
        cp /tmp/pmos.rsa.pub /etc/apk/keys/build.postmarketos.org.rsa.pub
        cp /tmp/pmos.rsa.pub /target/etc/apk/keys/build.postmarketos.org.rsa.pub
        cp /tmp/repositories /target/etc/apk/repositories
        cp /tmp/repositories /etc/apk/repositories
        apk update >/dev/null
        set +e
        apk --root /target \
            --initdb \
            --keys-dir /target/etc/apk/keys \
            --repositories-file /target/etc/apk/repositories \
            --update-cache \
            --no-interactive \
            add $PACKAGE_MANIFEST >/tmp/apk-manifest.log 2>&1
        rc_manifest=\$?
        set -e
        cat /tmp/apk-manifest.log
        if [ \"\$rc_manifest\" -ne 0 ]; then
            echo \"WARN: full manifest install returned non-zero (\$rc_manifest); retrying base set...\" >&2
        fi
        # Retry pass with just the BASE + PMOS sets so a missing optional
        # package (parity / profile extra) doesn't sink the whole bootstrap.
        set +e
        apk --root /target \
            --keys-dir /target/etc/apk/keys \
            --repositories-file /target/etc/apk/repositories \
            --no-interactive \
            add ${BASE_APK_PACKAGES[*]} ${PMOS_APK_PACKAGES[*]} >/tmp/apk-base.log 2>&1
        rc=\$?
        set -e
        cat /tmp/apk-base.log
        if [ \"\$rc\" -ne 0 ]; then
            # apk returns non-zero when ANY post-install or trigger script
            # fails, even though all packages installed correctly. The
            # postmarketos-mkinitfs trigger commonly fails on first
            # bootstrap because /usr/sbin/losetup does not exist yet
            # (Alpine ships it at /sbin/losetup; pmOS hook expects
            # /usr/sbin/losetup). The post-bootstrap fixup step below
            # symlinks the binary and re-runs mkinitfs, so this trigger
            # failure is recoverable. Distinguish recoverable trigger
            # failures from true package install errors.
            non_trigger_errors=\$(
                grep -E '^ERROR:' /tmp/apk-base.log \
                | grep -Ev 'apk/exec/postmarketos-mkinitfs-[^ ]+\\.trigger:' \
                || true
            )
            if [ -n \"\$non_trigger_errors\" ]; then
                echo \"ERROR: base+pmOS package install failed (\$rc) with non-trigger errors:\" >&2
                printf '%s\\n' \"\$non_trigger_errors\" >&2
                exit \"\$rc\"
            fi
            echo \"NOTE: apk exited \$rc but only postmarketos-mkinitfs trigger errors were reported; will regenerate initramfs in post-bootstrap fixup.\" >&2
        fi
        # Hard fail only when bootstrap produced an obviously unusable rootfs.
        test -x /target/bin/sh
        test -x /target/usr/sbin/sshd
        test -x /target/usr/bin/mkbootimg
        test -d /target/lib/modules
    "

##############################################################################
# Step 1.5: post-bootstrap mkinitfs fixup.
#
# Alpine ships losetup at /sbin/losetup; postmarketos-mkinitfs hook
# 00-initramfs-base.files lists /usr/sbin/losetup. Without the symlink
# below, the trigger fails with:
#   hookfiles: unable to add "/usr/sbin/losetup": getFile: failed to stat
#   file "/usr/sbin/losetup": stat /usr/sbin/losetup: no such file or
#   directory
# The pmbootstrap path side-steps this by patching the hook .files in
# its pmaports cache (apply_mkinitfs_*_compat_in_pmaports_cache); we
# cannot do that with binary apks, so we fix the path in the rootfs and
# re-run mkinitfs. Hard-fails if no initramfs lands in /target/boot/.
##############################################################################
echo "=== build-fairphone4: post-bootstrap mkinitfs + boot-deploy fixup ==="
"$ENGINE" run --rm --privileged --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        # ---- losetup path fix --------------------------------------------
        # Ensure /usr/sbin/losetup exists. losetup package installs to
        # /sbin/losetup on Alpine edge regardless of usrmerge state.
        if [ ! -e /target/usr/sbin/losetup ]; then
            if [ -e /target/sbin/losetup ]; then
                mkdir -p /target/usr/sbin
                ln -sf ../../sbin/losetup /target/usr/sbin/losetup
                echo "fixup: created /usr/sbin/losetup -> /sbin/losetup"
            else
                echo "ERROR: /target/sbin/losetup is missing; losetup apk did not install correctly." >&2
                ls -la /target/sbin/ /target/usr/sbin/ 2>/dev/null | head -40 >&2 || true
                exit 1
            fi
        fi

        # ---- mkinitfs hook compat patches --------------------------------
        # Same compat patches the pmbootstrap path applies to the pmaports
        # cache (apply_mkinitfs_*_compat_in_pmaports_cache) but applied to
        # the *installed* hook files in the rootfs since we use binary apks.
        for f in /target/usr/share/mkinitfs/files/*.files \
                 /target/etc/mkinitfs/files/*.files; do
            [ -f "$f" ] || continue
            if grep -q "udev/udev.conf" "$f" 2>/dev/null; then
                sed -i "/udev\\/udev\\.conf/d" "$f"
                echo "fixup: patched udev.conf reference out of $f"
            fi
        done

        # ---- chroot bind mounts ------------------------------------------
        # boot-deploy (called by postmarketos-mkinitfs as the deploy stage)
        # invokes:
        #   df --output=avail <tempdir>            -> needs /proc/mounts
        #   bc -l (multi-char vars like "available") -> needs GNU bc
        # Without /proc bind-mounted into the chroot, df fails with
        # "can'\''t find mount point". Without GNU bc, the script
        # short-circuits to "sh: invalid number ''\'\'\''". coreutils + bc
        # are now in the bootstrap manifest; the missing piece is the
        # virtual filesystems.
        for fs in proc sys dev dev/pts; do
            mkdir -p /target/$fs
        done
        mount -t proc proc        /target/proc
        mount -t sysfs sysfs      /target/sys
        mount --bind /dev         /target/dev
        mount --bind /dev/pts     /target/dev/pts 2>/dev/null || mount -t devpts devpts /target/dev/pts
        cleanup() {
            umount /target/dev/pts 2>/dev/null || true
            umount /target/dev     2>/dev/null || true
            umount /target/sys     2>/dev/null || true
            umount /target/proc    2>/dev/null || true
        }
        trap cleanup EXIT INT TERM

        # ---- regenerate initramfs (and trigger boot-deploy) --------------
        # Force /usr/bin first so chroot picks up GNU coreutils (df) and
        # GNU bc (multi-char variable names) ahead of the busybox shadows
        # in /bin and /sbin.
        echo "fixup: regenerating initramfs"
        if [ -x /target/sbin/postmarketos-mkinitfs ] || [ -x /target/usr/sbin/postmarketos-mkinitfs ]; then
            chroot /target /usr/bin/env PATH=/usr/bin:/usr/sbin:/sbin:/bin postmarketos-mkinitfs
        else
            chroot /target /usr/bin/env PATH=/usr/bin:/usr/sbin:/sbin:/bin mkinitfs
        fi

        # ---- post-mkinitfs assertions ------------------------------------
        if ! ls /target/boot/initramfs* >/dev/null 2>&1; then
            echo "ERROR: post-fixup mkinitfs run did not produce any initramfs in /target/boot/." >&2
            ls -la /target/boot/ >&2
            exit 2
        fi
        echo "fixup: initramfs files now under /target/boot/:"
        ls -la /target/boot/initramfs* >&2
        # boot-deploy normally also drops boot.img-<flavor> + a
        # combined boot.img into /target/boot/; report what it did so
        # Step 6 can pick it up directly.
        if ls /target/boot/boot.img* >/dev/null 2>&1; then
            echo "fixup: boot-deploy produced boot.img file(s):"
            ls -la /target/boot/boot.img* >&2
        else
            echo "fixup: WARN no boot.img under /target/boot/ after mkinitfs; Step 6 will assemble manually." >&2
        fi
    '

##############################################################################
# Step 2: base rootfs configuration (FP4-specific user/services/fstab).
##############################################################################
echo "=== build-fairphone4: base rootfs configuration ==="
"$ENGINE" run --rm --platform "linux/arm64" \
    -e PROFILE_NAME="$PROFILE_NAME" \
    -e INSTALL_PASSWORD="$INSTALL_PASSWORD" \
    -e PMOS_USER_UID="$PMOS_USER_UID" \
    -v "$ROOTFS_VOLUME:/target" \
    -v "$ROOT_DIR:/iso:ro" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        mkdir -p /target/etc /target/boot /target/etc/network /target/etc/conf.d
        printf "%s\n" "$PROFILE_NAME" > /target/etc/hostname

        # FP4 mounts dynamic partitions via make-dynpart-mappings;
        # /etc/fstab only needs the bind for /boot if any (handled by
        # postmarketos-initramfs). Leave a minimal fstab so OpenRC
        # mountall is happy.
        cat > /target/etc/fstab <<EOF
proc            /proc           proc    defaults        0 0
sysfs           /sys            sysfs   defaults        0 0
devpts          /dev/pts        devpts  defaults        0 0
tmpfs           /tmp            tmpfs   defaults        0 0
EOF

        mkdir -p /target/etc/runlevels/sysinit /target/etc/runlevels/boot /target/etc/runlevels/default
        # All runlevel symlinks are RELATIVE (../../init.d/X) for two
        # reasons:
        #   1. They evaluate correctly whether the rootfs is mounted at
        #      / (on device) or /target (in this verify container) or
        #      /mnt/recovery (during a future repair pass). Absolute
        #      symlinks like `/etc/init.d/X` resolve against the host
        #      root when the verify container does `[ -f ]`, making the
        #      check spuriously fail even though the symlink is valid
        #      on-device.
        #   2. They match what `rc-update add X <runlevel>` produces on
        #      a real OpenRC system, so an on-device user running
        #      rc-update later wont end up with a mix of absolute and
        #      relative entries in /etc/runlevels/.
        # Sysinit
        ln -sf ../../init.d/udev          /target/etc/runlevels/sysinit/udev || true
        ln -sf ../../init.d/udev-trigger  /target/etc/runlevels/sysinit/udev-trigger || true
        ln -sf ../../init.d/udev-settle   /target/etc/runlevels/sysinit/udev-settle || true
        # Boot
        ln -sf ../../init.d/hostname      /target/etc/runlevels/boot/hostname || true
        ln -sf ../../init.d/bootmisc      /target/etc/runlevels/boot/bootmisc || true
        ln -sf ../../init.d/syslog        /target/etc/runlevels/boot/syslog || true
        ln -sf ../../init.d/modules       /target/etc/runlevels/boot/modules || true
        # Default (parity with build-qemu)
        ln -sf ../../init.d/cgroups          /target/etc/runlevels/default/cgroups || true
        ln -sf ../../init.d/dbus             /target/etc/runlevels/default/dbus || true
        ln -sf ../../init.d/haveged          /target/etc/runlevels/default/haveged || true
        ln -sf ../../init.d/chronyd          /target/etc/runlevels/default/chronyd || true
        ln -sf ../../init.d/udev-postmount   /target/etc/runlevels/default/udev-postmount || true
        ln -sf ../../init.d/bluetooth        /target/etc/runlevels/default/bluetooth || true
        ln -sf ../../init.d/iio-sensor-proxy /target/etc/runlevels/default/iio-sensor-proxy || true
        ln -sf ../../init.d/apk-polkit-server /target/etc/runlevels/default/apk-polkit-server || true
        ln -sf ../../init.d/elogind          /target/etc/runlevels/default/elogind || true
        ln -sf ../../init.d/sleep-inhibitor  /target/etc/runlevels/default/sleep-inhibitor || true
        ln -sf ../../init.d/openrc-settingsd /target/etc/runlevels/default/openrc-settingsd || true
        ln -sf ../../init.d/modemmanager     /target/etc/runlevels/default/modemmanager || true
        ln -sf ../../init.d/networkmanager   /target/etc/runlevels/default/networkmanager || true
        ln -sf ../../init.d/wpa_supplicant   /target/etc/runlevels/default/wpa_supplicant || true
        ln -sf ../../init.d/zram-init        /target/etc/runlevels/default/zram-init || true
        ln -sf ../../init.d/sshd             /target/etc/runlevels/default/sshd || true
        ln -sf ../../init.d/seatd            /target/etc/runlevels/default/seatd || true
        ln -sf ../../init.d/greetd           /target/etc/runlevels/default/greetd || true
        # rfkill: parity with postmarketos-base-ui-openrc post-install
        # (build-qemu also enables it). Keeps radio kill-switch state
        # consistent across reboots.
        ln -sf ../../init.d/rfkill           /target/etc/runlevels/default/rfkill || true
        # FP4-specific: hexagonrpcd is the userspace daemon for Qualcomm
        # remoteproc fastrpc (camera/sensors); device-fairphone-fp4-openrc
        # post-install symlinks it but only when openrc is the active
        # init at install time. Re-link defensively here.
        if [ -f /target/etc/init.d/hexagonrpcd ]; then
            ln -sf ../../init.d/hexagonrpcd /target/etc/runlevels/default/hexagonrpcd || true
        fi

        # postmarketos-base-ui / postmarketos-ui-phosh / postmarketos-base
        # configuration drops. Mirrors the build-qemu layout but pulls
        # from /iso/pmaports/main since the FP4 build uses the vendored
        # pmaports tree.
        mkdir -p /target/usr/share/glib-2.0/schemas \
                 /target/usr/share/applications \
                 /target/etc/xdg/autostart \
                 /target/etc/chrony \
                 /target/etc/elogind \
                 /target/etc/X11 \
                 /target/usr/lib/NetworkManager/conf.d \
                 /target/usr/lib/NetworkManager/dispatcher.d \
                 /target/usr/share/wireplumber/wireplumber.conf.d \
                 /target/usr/lib/udev/rules.d \
                 /target/usr/share/mkinitfs/files \
                 /target/usr/share/flatpak/remotes.d \
                 /target/etc/profile.d \
                 /target/etc/skel
        PM=/iso/pmaports/main
        if [ -f "$PM/postmarketos-ui-phosh/01_postmarketos-ui-phosh.gschema.override" ]; then
            install -Dm644 "$PM/postmarketos-ui-phosh/01_postmarketos-ui-phosh.gschema.override" \
                /target/usr/share/glib-2.0/schemas/01_postmarketos-ui-phosh.gschema.override
        fi
        if [ -f "$PM/postmarketos-ui-phosh/mimeapps.list" ]; then
            install -Dm644 "$PM/postmarketos-ui-phosh/mimeapps.list" \
                /target/usr/share/applications/mimeapps.list
        fi
        if [ -f "$PM/postmarketos-ui-phosh/udiskie.desktop" ]; then
            install -Dm644 "$PM/postmarketos-ui-phosh/udiskie.desktop" \
                /target/etc/xdg/autostart/udiskie.desktop
        fi
        if [ -f "$PM/postmarketos-base-ui-gnome/00_postmarketos-base-ui-gnome.gschema.override" ]; then
            install -Dm644 "$PM/postmarketos-base-ui-gnome/00_postmarketos-base-ui-gnome.gschema.override" \
                /target/usr/share/glib-2.0/schemas/00_postmarketos-base-ui-gnome.gschema.override
        fi
        # Recompile schemas so the gsettings overrides take effect.
        glib-compile-schemas /target/usr/share/glib-2.0/schemas/ 2>/dev/null || true

        # Run device-fairphone-fp4 post-install equivalents: drop UCM
        # (already shipped by the apk), wireplumber rule, and udev rule.
        # The apk install handles this when /etc/init.d hooks fire, but
        # apk --root mode skips trigger scripts; re-run the file install
        # manually here so the rootfs ships them.
        if [ -d /target/usr/share/alsa/ucm2/Fairphone/fp4 ]; then
            : # already shipped by device-fairphone-fp4
        fi

        # Create XDG_RUNTIME_DIR for the user session.
        mkdir -p "/target/run/user/${PMOS_USER_UID}"
        chmod 700 "/target/run/user/${PMOS_USER_UID}"

        # Hash the install password.
        apk add --no-cache openssl >/dev/null 2>&1 || true
        pass_hash="$(openssl passwd -6 "$INSTALL_PASSWORD" 2>/dev/null || true)"
        if [ -z "$pass_hash" ]; then
            apk add --no-cache libxcrypt >/dev/null 2>&1 || true
            pass_hash="$(echo "$INSTALL_PASSWORD" | mkpasswd -s -m sha-512 2>/dev/null || true)"
        fi
        [ -n "$pass_hash" ] || { echo "ERROR: could not generate password hash" >&2; exit 1; }
        awk -F: -v h="$pass_hash" '"'"'BEGIN{OFS=":"} $1=="root"{$2=h} {print}'"'"' /target/etc/shadow > /target/etc/shadow.new
        mv /target/etc/shadow.new /target/etc/shadow
        mkdir -p /target/home/user
        printf "user:x:%s:%s:AtomOS User:/home/user:/bin/bash\n" "${PMOS_USER_UID}" "${PMOS_USER_UID}" >> /target/etc/passwd
        printf "user:x:%s:\n" "${PMOS_USER_UID}" >> /target/etc/group
        # Group membership matches pmbootstrap '"'"'install_user_groups'"'"' +
        # postmarketos-ui-phosh _pmb_groups + pmaports per-UI extras.
        # Critical entries:
        #   wheel     - sudo
        #   video     - /dev/dri/card0 (DRI rendering)
        #   render    - /dev/dri/renderD128 (GPU compute; phoc/wlroots
        #               increasingly require this and silently fail to
        #               initialise without it)
        #   audio     - /dev/snd/* (sound)
        #   input     - /dev/input/* (touchscreen, keyboard, sensors)
        #   plugdev   - USB device access (libimobiledevice, gphoto2, ...)
        #   seat      - seatd socket (REQUIRED for ANY wlroots compositor
        #               including phoc; without this greetd cannot
        #               acquire a seat and exits before phrog ever runs)
        #   netdev    - NetworkManager DBus introspection
        #   dialout   - modem TTY (ModemManager occasionally falls back
        #               to ttyMSM for vendor AT commands)
        #   bluetooth - bluez DBus access
        #   feedbackd - haptic feedback (postmarketos-ui-phosh _pmb_groups)
        for grp in wheel video render audio input plugdev seat netdev dialout bluetooth feedbackd; do
            if grep -q "^${grp}:" /target/etc/group 2>/dev/null; then
                sed -i "s/^${grp}:\\([^:]*\\):\\([^:]*\\):\\(.*\\)$/${grp}:\\1:\\2:\\3,user/" /target/etc/group
                sed -i "s/:,user/:user/" /target/etc/group
            else
                # Auto-create with a high GID for groups that the base
                # rootfs did not pre-populate (e.g. dialout on a
                # systemd-less Alpine where it is not a default group).
                printf "%s:x:100:user\n" "$grp" >> /target/etc/group || true
            fi
        done
        printf "user:%s:19000:0:99999:7:::\n" "$pass_hash" >> /target/etc/shadow
        chown -R "${PMOS_USER_UID}:${PMOS_USER_UID}" /target/home/user || true
        mkdir -p /target/run/user
        chmod 755 /target/run/user
        mkdir -p /target/home/user/.config
        printf "%s\n" "export XDG_RUNTIME_DIR=/run/user/${PMOS_USER_UID}" > /target/home/user/.bash_profile
        printf "%s\n" "export XDG_SESSION_TYPE=wayland" >> /target/home/user/.bash_profile
        printf "%s\n" "export XDG_CURRENT_DESKTOP=Phosh:GNOME" >> /target/home/user/.bash_profile
        printf "%s\n" "export WAYLAND_DISPLAY=wayland-0" >> /target/home/user/.bash_profile
        chown -R "${PMOS_USER_UID}:${PMOS_USER_UID}" /target/home/user/.config

        # Sshd policy sanitize (UsePAM is unsupported in this image path).
        if [ -f /target/etc/ssh/sshd_config.d/50-postmarketos-ui-policy.conf ]; then
            sed -i "/^[[:space:]]*UsePAM[[:space:]]\\+/d" /target/etc/ssh/sshd_config.d/50-postmarketos-ui-policy.conf
        fi
        # Pre-generate SSH host keys.
        if [ -x /target/usr/bin/ssh-keygen ]; then
            chroot /target /usr/bin/ssh-keygen -A >/dev/null 2>&1 || true
        fi

        # Greetd config (parity with build-qemu). Only write if the apk
        # did not already drop one (postmarketos-ui-phosh ships its own
        # greetd.confd that does the same thing).
        if [ ! -f /target/etc/conf.d/greetd ] || ! grep -q "phrog/greetd-config.toml" /target/etc/conf.d/greetd; then
            cat > /target/etc/conf.d/greetd <<GREETD_CONFD
cfgfile="/etc/phrog/greetd-config.toml"
GREETD_CONFD
        fi
    '

##############################################################################
# Step 2.5: re-run user-touching post-install scripts inside a privileged chroot.
#
# `apk --root /target add` runs post-installs via QEMU user-mode emulation
# during package install. That works for most scripts, but two classes
# routinely misbehave:
#
#   1. Post-installs that touch user accounts (usermod -aG ...): the
#      target user (UID 10000) was created by us AFTER the apk add
#      transaction, so anything that ran usermod against that uid during
#      the apk pass was a no-op silently.
#
#   2. Post-installs that depend on running services or sockets being
#      reachable: the qemu-user emulation layer cannot start daemons,
#      so any post-install relying on dbus / elogind being live during
#      install is skipped.
#
# postmarketos-ui-phosh.post-install does exactly case 1:
#   default_user=$(getent passwd "10000" | cut -d: -f1)
#   if [ -n "$default_user" ]; then
#       usermod -aG feedbackd "$default_user"
#   fi
# When this ran during apk install, the user did not exist yet, so the
# usermod was a no-op. We re-run those scripts here against the now-
# populated rootfs so the user lands in feedbackd / video / render /
# seat / wheel / netdev / dialout / bluetooth groups for real.
##############################################################################
echo "=== build-fairphone4: re-run user-touching post-install scripts in chroot ==="
"$ENGINE" run --rm --privileged --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        for fs in proc sys dev dev/pts; do mkdir -p /target/$fs; done
        mount -t proc proc        /target/proc
        mount -t sysfs sysfs      /target/sys
        mount --bind /dev         /target/dev
        mount --bind /dev/pts     /target/dev/pts 2>/dev/null || mount -t devpts devpts /target/dev/pts
        cleanup() {
            umount /target/dev/pts 2>/dev/null || true
            umount /target/dev     2>/dev/null || true
            umount /target/sys     2>/dev/null || true
            umount /target/proc    2>/dev/null || true
        }
        trap cleanup EXIT INT TERM

        # ---- ensure system users created by post-install scripts exist ----
        # Alpine s `greetd` apk creates a system user `greetd:greetd`
        # via post-install. When apk --root /target add runs that
        # post-install via QEMU user-mode emulation, the addgroup/adduser
        # calls sometimes silently fail to write to /target/etc/passwd
        # (the binfmt layer cannot reliably acquire the lockfile under
        # heavy parallel install). When the user is missing, greetd
        # exits at startup with "ERROR: user.greetd failed to start" --
        # that exact message format comes from greetd reporting the
        # named system user it could not setuid() to.
        #
        # Create it explicitly here as a system user (UID < 1000), with
        # the conventions Alpine uses: locked password, /sbin/nologin
        # shell, /var/lib/greetd home. Idempotent: skip if already there.
        # HARD-FAIL with diagnostic if creation does not succeed --
        # silently shipping a rootfs without the greetd user causes the
        # exact "ERROR: user.greetd failed to start" boot loop the user
        # has been hitting.
        if ! chroot /target /bin/sh -c "getent group greetd >/dev/null 2>&1"; then
            echo "fixup: creating greetd system group"
            if ! chroot /target /bin/sh -c "addgroup -S greetd"; then
                echo "FATAL: addgroup -S greetd failed inside chroot." >&2
                echo "       /target/etc/group head:" >&2
                head -20 /target/etc/group >&2
                exit 11
            fi
        fi
        if ! chroot /target /bin/sh -c "getent passwd greetd >/dev/null 2>&1"; then
            echo "fixup: creating greetd system user"
            # Alpine busybox adduser flags: -S system, -D no password,
            # -H no home dir create, -G primary group, -s shell.
            if ! chroot /target /bin/sh -c "
                mkdir -p /var/lib/greetd
                adduser -S -D -H -G greetd -h /var/lib/greetd -s /sbin/nologin greetd
                chown -R greetd:greetd /var/lib/greetd
                chmod 0755 /var/lib/greetd
            "; then
                echo "FATAL: adduser greetd failed inside chroot." >&2
                echo "       /target/etc/passwd head:" >&2
                head -20 /target/etc/passwd >&2
                exit 12
            fi
        fi
        # Re-verify creation actually persisted to /target/etc/passwd
        # (busybox adduser sometimes returns 0 but writes nothing when
        # the lockfile path is unwriteable from the qemu-emulated env).
        if ! chroot /target /bin/sh -c "getent passwd greetd >/dev/null 2>&1"; then
            echo "FATAL: greetd account still missing AFTER addgroup+adduser succeeded." >&2
            echo "       This is the bug that produces ERROR: user.greetd failed to start at boot." >&2
            echo "       /target/etc/passwd grep:" >&2
            grep -i greetd /target/etc/passwd /target/etc/group /target/etc/shadow >&2 || true
            echo "       /target permissions:" >&2
            ls -la /target/etc/{passwd,group,shadow} >&2 || true
            exit 13
        fi
        echo "fixup: greetd account confirmed in /target/etc/passwd:"
        chroot /target /bin/sh -c "getent passwd greetd; getent group greetd" | sed "s/^/  /"

        # Add greetd user to seat/video/input groups so the greeter
        # process can drive the wlroots compositor.
        for grp in seat video input render; do
            if chroot /target /bin/sh -c "getent group $grp >/dev/null 2>&1"; then
                chroot /target /bin/sh -c "addgroup greetd $grp" >/dev/null 2>&1 || true
            fi
        done

        # Re-run any cached apk post-install script that touches the
        # default user. apk stores the post-install scripts it ran during
        # `apk add` under /lib/apk/scripts/<pkg>-<ver>.post-install.
        # Re-running them is safe (usermod -aG is idempotent).
        for f in /target/lib/apk/scripts/postmarketos-ui-phosh-*.post-install \
                 /target/var/lib/apk/scripts/postmarketos-ui-phosh-*.post-install \
                 /target/lib/apk/scripts/postmarketos-base-ui-*.post-install; do
            [ -f "$f" ] || continue
            rel="${f#/target}"
            echo "rerun: $rel"
            chroot /target sh "$rel" 2>&1 | sed "s/^/  /" || echo "  (post-install rc=$? ignored)" >&2
        done

        # Force-add the user to canonical groups via in-chroot usermod,
        # in case our /etc/group hand-edit conflicted with apk group
        # creation timing (e.g. apk created the video group with a
        # specific gid AFTER we hand-appended the user to it).
        for grp in wheel video render audio input plugdev seat netdev dialout bluetooth feedbackd; do
            if chroot /target /bin/sh -c "getent group $grp >/dev/null 2>&1"; then
                # busybox addgroup syntax: addgroup <user> <group>
                chroot /target /bin/sh -c "addgroup user $grp" >/dev/null 2>&1 || true
                # GNU shadow usermod syntax: usermod -aG <group> <user>
                chroot /target /bin/sh -c "usermod -aG $grp user" >/dev/null 2>&1 || true
            fi
        done

        echo "build-fairphone4: final user identity in rootfs:"
        chroot /target /bin/sh -c "id user" >&2
        echo "build-fairphone4: greetd system user in rootfs:"
        chroot /target /bin/sh -c "id greetd 2>&1 || true" >&2
    '

##############################################################################
# Step 3: build/install custom phosh + Rust components in heavy container.
##############################################################################
echo "=== build-fairphone4: build/install custom phosh + Rust components ==="
PHOSH_SRC="$ROOT_DIR/rust/phosh/phosh"
USE_VENDOR_PHOSH=1
if [ ! -f "$PHOSH_SRC/meson.build" ]; then
    echo "WARN: rust/phosh/phosh/meson.build missing; skipping vendor phosh build (using stock pmOS phosh)." >&2
    USE_VENDOR_PHOSH=0
fi
# Honor the same opt-in toggle the pmbootstrap path uses for FP4 so this
# script stays bisectable against build-image.sh.
if [ "${ATOMOS_ENABLE_VENDOR_PHOSH_ON_FP4:-0}" != "1" ] \
   && [ "${ATOMOS_ENABLE_VENDOR_PHOSH:-0}" != "1" ] \
   && [ "${ATOMOS_SKIP_VENDOR_PHOSH_BUILD:-0}" != "1" ]; then
    echo "build-fairphone4: defaulting to stock phosh (set ATOMOS_ENABLE_VENDOR_PHOSH_ON_FP4=1 to opt in)."
    USE_VENDOR_PHOSH=0
fi

# build_container_script copied verbatim from build-qemu.sh and adjusted
# only to gate vendor phosh behind USE_VENDOR_PHOSH (FP4 typically ships
# stock phosh per the build-image.sh policy). Any future fixes to the
# build-qemu version should be ported here.
build_container_script='
set -eu
printf "%s\n" \
  "https://dl-cdn.alpinelinux.org/alpine/v3.21/main" \
  "https://dl-cdn.alpinelinux.org/alpine/v3.21/community" \
  "https://dl-cdn.alpinelinux.org/alpine/edge/main" \
  "https://dl-cdn.alpinelinux.org/alpine/edge/community" \
  "https://dl-cdn.alpinelinux.org/alpine/edge/testing" \
  "'"$PMOS_REPO_URL"'" > /etc/apk/repositories
mkdir -p /etc/apk/keys
cp /tmp/pmos.rsa.pub /etc/apk/keys/build.postmarketos.org.rsa.pub
apk update >/dev/null
apk add --no-interactive \
  build-base git meson ninja-build pkgconf \
  rust cargo \
  glib-dev gtk4.0-dev libadwaita-dev \
  evolution-data-server-dev \
  gnome-bluetooth-dev \
  gnome-desktop-dev \
  libgudev-dev \
  libhandy1-dev \
  callaudiod-dev \
  feedbackd-dev \
  pulseaudio-dev \
  networkmanager-dev \
  modemmanager-dev \
  upower-dev \
  evince-dev \
  qrcodegen-dev \
  polkit-dev \
  elogind-dev \
  webkit2gtk-6.0-dev gstreamer-dev \
  gobject-introspection-dev vala \
  wayland-dev wayland-protocols \
  libxkbcommon-dev dbus-dev linux-pam-dev \
  pango-dev cairo-dev gdk-pixbuf-dev libsoup3-dev json-glib-dev
apk add --no-interactive gtk4-layer-shell-dev >/dev/null 2>&1 \
  || apk add --no-interactive gtk4-layer-shell >/dev/null 2>&1 || true

mkdir -p /usr/local/bin
cat > /usr/local/bin/ar <<"AR_SHIM"
#!/bin/sh
if [ "$#" -eq 0 ]; then exec /usr/bin/ar; fi
_first="$1"; shift
case "$_first" in
    --*) ;;
    -[a-zA-Z]*|[a-zA-Z]*) _first=$(printf "%s" "$_first" | tr -d "T") ;;
esac
exec /usr/bin/ar "$_first" "$@"
AR_SHIM
chmod 0755 /usr/local/bin/ar
export PATH="/usr/local/bin:$PATH"
export AR="/usr/local/bin/ar"
ulimit -n 65536 2>/dev/null || true

apk add --no-interactive ccache file >/dev/null 2>&1 || true
if command -v ccache >/dev/null 2>&1; then
    export CCACHE_DIR=/cache/.ccache
    mkdir -p "$CCACHE_DIR"
    export CCACHE_COMPRESS=1
    export CCACHE_MAXSIZE="${ATOMOS_CCACHE_MAXSIZE:-5G}"
    export CC="ccache gcc"
    export CXX="ccache g++"
fi

meson_cache_setup() {
    _build_dir="$1"; shift
    _src_dir="$1"; shift
    _hash=$(printf "%s\n" "$_src_dir" "CC=${CC:-}" "CXX=${CXX:-}" "AR=${AR:-}" "$@" \
            | sha256sum | cut -d" " -f1)
    _marker="$_build_dir/.atomos-meson-args"
    if [ -f "$_build_dir/build.ninja" ] && [ -f "$_marker" ] \
        && [ "$(cat "$_marker" 2>/dev/null)" = "$_hash" ]; then
        echo "build-fairphone4: reusing meson cache: $_build_dir"
    elif [ -f "$_build_dir/build.ninja" ]; then
        echo "build-fairphone4: meson args changed -> reconfigure: $_build_dir"
        meson setup --reconfigure "$_build_dir" "$_src_dir" "$@"
        printf "%s" "$_hash" > "$_marker"
    else
        rm -rf "$_build_dir"
        mkdir -p "$(dirname "$_build_dir")"
        meson setup "$_build_dir" "$_src_dir" "$@"
        printf "%s" "$_hash" > "$_marker"
    fi
    unset _build_dir _src_dir _hash _marker
}

if [ "${USE_VENDOR_PHOSH:-0}" = "1" ]; then
    GMOBILE_DIR=/work/iso-postmarketos/rust/phosh/phosh/subprojects/gmobile
    GMOBILE_BUILD=/cache/gmobile
    if [ -f "$GMOBILE_DIR/meson.build" ]; then
        echo "Building gmobile from: $GMOBILE_DIR"
        meson_cache_setup "$GMOBILE_BUILD" "$GMOBILE_DIR" --prefix=/usr -Dtests=false -Dgtk_doc=false
        ninja -C "$GMOBILE_BUILD"
        ninja -C "$GMOBILE_BUILD" install
        DESTDIR=/target ninja -C "$GMOBILE_BUILD" install
    fi
    export PKG_CONFIG_PATH="/target/usr/lib/pkgconfig:/target/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
    PHOSH_BUILD=/cache/phosh
    meson_cache_setup "$PHOSH_BUILD" /work/iso-postmarketos/rust/phosh/phosh --prefix=/usr -Dtests=false
    ninja -C "$PHOSH_BUILD"
    ninja -C "$PHOSH_BUILD" install
    DESTDIR=/target ninja -C "$PHOSH_BUILD" install
fi

# Overview chat UI (always built; container is aarch64-musl native).
cargo build --manifest-path /work/iso-postmarketos/rust/atomos-overview-chat-ui/Cargo.toml \
    -p atomos-overview-chat-ui-app --release --bin atomos-overview-chat-ui
install -d /target/usr/local/bin /target/usr/libexec
install -m 0755 /work/iso-postmarketos/rust/atomos-overview-chat-ui/target/release/atomos-overview-chat-ui \
    /target/usr/local/bin/atomos-overview-chat-ui
ln -sf ../local/bin/atomos-overview-chat-ui /target/usr/bin/atomos-overview-chat-ui

# home-bg.
if [ "${BUILD_HOME_BG:-0}" = "1" ] && [ -f /work/iso-postmarketos/rust/atomos-home-bg/app-gtk/Cargo.toml ]; then
    cargo build --manifest-path /work/iso-postmarketos/rust/atomos-home-bg/app-gtk/Cargo.toml \
        --release --bin atomos-home-bg
    test -x /work/iso-postmarketos/rust/atomos-home-bg/target/release/atomos-home-bg
fi

if [ "${BUILD_APP_HANDLER:-0}" = "1" ] && [ -f /work/iso-postmarketos/rust/atomos-app-handler/app-gtk/Cargo.toml ]; then
    cargo build --manifest-path /work/iso-postmarketos/rust/atomos-app-handler/app-gtk/Cargo.toml \
        --release --bin atomos-app-handler
    test -x /work/iso-postmarketos/rust/atomos-app-handler/target/release/atomos-app-handler
fi

apk add --no-interactive glib >/dev/null 2>&1 || true
glib-compile-schemas /target/usr/share/glib-2.0/schemas/ 2>/dev/null || true
'

"$ENGINE" run --rm --platform "linux/arm64" \
    --ulimit nofile=65536:65536 \
    -v "$ROOTFS_VOLUME:/target" \
    -v "$REPO_TOP:/work" \
    -v "$MESON_CACHE_MOUNT:/cache" \
    -v "$PMOS_KEY_HOST:/tmp/pmos.rsa.pub:ro" \
    -e BUILD_HOME_BG="$BUILD_HOME_BG" \
    -e BUILD_APP_HANDLER="$BUILD_APP_HANDLER" \
    -e USE_VENDOR_PHOSH="$USE_VENDOR_PHOSH" \
    "$ALPINE_IMAGE" /bin/sh -c "$build_container_script"

##############################################################################
# Step 4: direct rootfs install of AtomOS overlays (parity with build-qemu).
##############################################################################
echo "=== build-fairphone4: apply AtomOS overlays (direct rootfs mode) ==="
# shellcheck source=scripts/_lib-rootfs-overlays.sh
source "$ROOT_DIR/scripts/_lib-rootfs-overlays.sh"
atomos_apply_overlays

# NOTE: deliberately NOT calling scripts/rootfs/apply-overlay.sh,
# scripts/phosh/apply-atomos-phosh-dconf.sh, or
# scripts/rootfs/apply-atomos-wallpaper-dconf.sh here even though
# build-image.sh (the pmbootstrap path) does call all three.
#
# We tried adding them in a "Step 4.5" container that ran each in
# `--rootfs /target` mode. The result was a device that booted to greetd
# failing immediately with "ERROR: user.greetd failed to start". The
# failure went away the moment the step was removed.
#
# Likely culprit was apply-overlay.sh's chroot-into-/target operation:
# its OVERLAY_SCRIPT runs `systemctl enable sshd.service` /
# `systemctl enable usb-moded.service` inside `chroot /target /bin/sh`
# (because /target/bin/systemctl is present from the systemd-edge stack
# we installed). Inside an offline chroot with no /run/systemd, no
# /sys/fs/cgroup, and no PID 1, systemctl's enable path can fall through
# to side effects that perturb the rootfs's user/group state -- including
# undoing the explicit greetd system-user creation Step 2.5
# (build-fairphone4.sh:922-1016) does specifically to defeat the
# "ERROR: user.greetd failed to start" boot loop the FP4 has historically
# hit. apply-atomos-wallpaper-dconf.sh's chroot block (which runs runuser
# / su as uid 10000 and writes per-user dconf) has not been ruled out
# either.
#
# build-qemu.sh ships working customizations (vendor phosh + chat UI +
# home-bg + wallpaper + sshd hardening) WITHOUT apply-overlay.sh --
# install-overview-chat-ui.sh (with ATOMOS_OVERVIEW_CHAT_UI_INSTALL_
# AUTOSTART=1) drops the XDG autostart alongside the launcher.
#
# If we ever want OS branding ("Atom OS" PRETTY_NAME) or the dconf
# overrides on FP4, port them as direct file writes from the existing
# Step 4 customization container (mkdir + sed + cat directly into
# /target/etc/...) rather than via chroot -- skipping the systemctl
# subshell entirely.

##############################################################################
# Step 4.9: greetd guarantee sweep (HOTFIX -- ports the v2 fix backwards).
#
# Defends against the on-device "ERROR: user.greetd failed to start"
# boot loop. The sweep is:
#   - direct-write the greetd user/group/shadow rows if they're missing
#     (no busybox adduser, so unaffected by the qemu-user lockfile race
#     that has historically broken this rootfs);
#   - ensure /var/lib/greetd exists with mode 0750 owner=greetd:greetd
#     (greetd.initd's start_pre fails on missing/empty homedir);
#   - remove any stray /etc/runlevels/*/user.greetd or
#     /etc/init.d/user.greetd (OpenRC's user-service wrapper logs the
#     exact "ERROR: user.greetd failed to start" message for that
#     service name, even when the regular `greetd` service is enabled);
#   - parse /etc/phrog/greetd-config.toml + /etc/greetd/config.toml so
#     we also cover any session user= override (not just hardcoded
#     "greetd").
# Body lives in scripts/_lib-greetd-guarantee-body.sh and is also used
# by build-fairphone4-v2.sh.
##############################################################################
if [ -f "$ROOT_DIR/scripts/_lib-greetd-guarantee-body.sh" ]; then
    echo "=== build-fairphone4: greetd guarantee sweep ==="
    "$ENGINE" run --rm --platform "linux/arm64" \
        -v "$ROOTFS_VOLUME:/target" \
        -v "$ROOT_DIR/scripts/_lib-greetd-guarantee-body.sh:/lib-greetd-guarantee-body.sh:ro" \
        "$ALPINE_IMAGE" /bin/sh /lib-greetd-guarantee-body.sh
else
    echo "WARN: scripts/_lib-greetd-guarantee-body.sh missing; skipping greetd guarantee." >&2
fi

##############################################################################
# Step 5: final verification (mirror build-qemu's check_x/check_grep set).
##############################################################################
echo "=== build-fairphone4: final verification ==="
"$ENGINE" run --rm --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target" \
    -e BUILD_OVERVIEW_CHAT_UI="$BUILD_OVERVIEW_CHAT_UI" \
    -e BUILD_HOME_BG="$BUILD_HOME_BG" \
    -e BUILD_APP_HANDLER="$BUILD_APP_HANDLER" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        FAIL=0
        check_x() { if [ -x "$1" ]; then echo "  ok  -x $1"; else echo "  FAIL -x $1" >&2; FAIL=1; fi; }
        check_f() { if [ -f "$1" ]; then echo "  ok  -f $1"; else echo "  FAIL -f $1" >&2; FAIL=1; fi; }
        # check_link: succeeds for any path that EXISTS as either a
        # symlink or a regular file. Use this for /etc/runlevels/*/X
        # entries: those are absolute symlinks pointing at /etc/init.d/X
        # which only resolves correctly inside the rootfs. From the
        # verify container [ -f ] dereferences and looks for the host
        # filesystem path, which legitimately does not exist. We want to
        # know the *symlink* itself is in place; runtime resolution is
        # OpenRC s problem at boot. Even with the relative-symlink fix,
        # this is the more honest predicate to use.
        check_link() {
            if [ -L "$1" ] || [ -e "$1" ]; then
                if [ -L "$1" ]; then
                    echo "  ok  symlink $1 -> $(readlink "$1")"
                else
                    echo "  ok  exists $1"
                fi
            else
                echo "  FAIL symlink/exists $1" >&2
                FAIL=1
            fi
        }
        check_grep() {
            if [ -f "$2" ] && grep -q "$1" "$2"; then echo "  ok  grep $1 in $2"
            else echo "  FAIL grep $1 in $2" >&2; FAIL=1; fi
        }

        echo "--- core binaries ---"
        check_x /target/usr/libexec/phosh
        check_x /target/usr/sbin/sshd
        check_x /target/usr/bin/mkbootimg
        check_f /target/etc/ssh/ssh_host_ed25519_key
        check_f /target/etc/ssh/ssh_host_rsa_key

        echo "--- greetd / phrog wiring ---"
        # Greeter binary
        check_x /target/usr/bin/phrog
        check_x /target/usr/libexec/phrog-greetd-session
        # System service init scripts
        check_x /target/etc/init.d/greetd
        check_x /target/etc/init.d/seatd
        check_x /target/etc/init.d/elogind
        # Runlevel symlinks (use check_link, not check_f, because these
        # are absolute->/etc/init.d/X symlinks that only resolve inside
        # the rootfs).
        check_link /target/etc/runlevels/default/greetd
        check_link /target/etc/runlevels/default/seatd
        check_link /target/etc/runlevels/default/elogind
        # Configs
        check_f /target/etc/conf.d/greetd
        check_grep "phrog/greetd-config.toml" /target/etc/conf.d/greetd
        check_f /target/etc/phrog/greetd-config.toml
        # CRITICAL: the system user that greetd switches to MUST exist.
        # Alpine s greetd-phrog config sets [default_session].user="greetd"
        # which means greetd execs setuid(getpwnam("greetd")). When
        # apk --root /target add runs greetd s post-install via qemu-user
        # emulation, addgroup/adduser sometimes silently fail, leaving
        # /etc/passwd without the greetd account. greetd then exits at
        # startup with the on-screen "ERROR: user.greetd failed to start"
        # message -- that "user.<name>" phrasing is greetd s own report
        # for "system user named <name> not found".
        if chroot /target /bin/sh -c "getent passwd greetd >/dev/null 2>&1"; then
            echo "  ok  greetd system user exists in rootfs"
            chroot /target /bin/sh -c "getent passwd greetd" | sed "s/^/    /"
        else
            echo "  FAIL greetd system user MISSING in /target/etc/passwd" >&2
            echo "       greetd will fail with \"user.greetd failed to start\" on boot." >&2
            echo "       Step 2.5 will create it; if you see this here something else broke." >&2
            FAIL=1
        fi
        echo "  --- /etc/conf.d/greetd ---"
        cat /target/etc/conf.d/greetd | sed "s/^/    /" || true
        echo "  --- /etc/phrog/greetd-config.toml ---"
        cat /target/etc/phrog/greetd-config.toml | sed "s/^/    /" || true
        echo "  --- /target/etc/runlevels/default/ ---"
        ls -l /target/etc/runlevels/default/ 2>/dev/null | sed "s/^/    /"
        echo "  --- groups for default user ---"
        chroot /target /bin/sh -c "id user" 2>&1 | sed "s/^/    /"

        echo "--- FP4 device package files ---"
        # device-fairphone-fp4 ships these (UCM, wireplumber rule, udev rule).
        check_f /target/usr/share/alsa/ucm2/Fairphone/fp4/HiFi.conf
        check_f /target/usr/share/alsa/ucm2/Fairphone/fp4/fp4.conf
        check_f /target/usr/share/wireplumber/wireplumber.conf.d/52-fairphone-fp4.conf
        check_f /target/usr/lib/udev/rules.d/81-libssc-fairphone-fp4.rules
        # Kernel + DTB (linux-postmarketos-qcom-sm6350 + appended DTB).
        if ls /target/boot/vmlinuz* >/dev/null 2>&1; then
            echo "  ok  found /target/boot/vmlinuz*"
        else
            echo "  FAIL no kernel image under /target/boot/" >&2; FAIL=1
        fi

        if [ "$BUILD_OVERVIEW_CHAT_UI" = "1" ]; then
            echo "--- atomos-overview-chat-ui files ---"
            check_x /target/usr/local/bin/atomos-overview-chat-ui
            check_x /target/usr/bin/atomos-overview-chat-ui
            check_x /target/usr/libexec/atomos-overview-chat-ui
        fi

        if [ "$BUILD_HOME_BG" = "1" ]; then
            echo "--- atomos-home-bg files ---"
            check_x /target/usr/local/bin/atomos-home-bg
            check_x /target/usr/bin/atomos-home-bg
            check_x /target/usr/libexec/atomos-home-bg
            check_f /target/usr/share/atomos-home-bg/index.html
            check_grep "ATOMOS_HOME_BG_ENABLE_RUNTIME" /target/usr/libexec/atomos-home-bg
            check_grep "atomos-home-bg.disabled"       /target/usr/libexec/atomos-home-bg
            check_grep "ATOMOS_HOME_BG_LAYER"          /target/usr/libexec/atomos-home-bg
            check_grep "ATOMOS_HOME_BG_INTERACTIVE"    /target/usr/libexec/atomos-home-bg
            check_f /target/etc/xdg/autostart/atomos-home-bg.desktop
            check_grep "Exec=/usr/libexec/atomos-home-bg --show" /target/etc/xdg/autostart/atomos-home-bg.desktop
            for lib in libwebkitgtk-6.0.so libgtk4-layer-shell.so libgtk-4.so; do
                if find /target/usr/lib /target/lib -name "${lib}*" -maxdepth 3 2>/dev/null | grep -q .; then
                    echo "  ok  found ${lib}*"
                else
                    echo "  FAIL ${lib}* not found" >&2; FAIL=1
                fi
            done
        fi

        if [ "$BUILD_APP_HANDLER" = "1" ]; then
            echo "--- atomos-app-handler files ---"
            check_x /target/usr/local/bin/atomos-app-handler
            check_x /target/usr/bin/atomos-app-handler
            check_x /target/usr/libexec/atomos-app-handler
            check_grep "ATOMOS_APP_HANDLER_ENABLE_RUNTIME" /target/usr/libexec/atomos-app-handler
            check_grep "atomos-app-handler.disabled" /target/usr/libexec/atomos-app-handler
            echo "--- atomos-app-handler hybrid lifecycle contract ---"
            check_f /target/etc/atomos/app-handler-contract
            check_grep "^app-handler-v1-launch-switcher-dbus-home$" /target/etc/atomos/app-handler-contract
            check_grep "action=show"    /target/usr/libexec/atomos-app-handler
            check_grep "action=hide"    /target/usr/libexec/atomos-app-handler
            check_grep "signal_show"    /target/usr/libexec/atomos-app-handler
            check_grep "signal_hide"    /target/usr/libexec/atomos-app-handler
            check_grep "kill -USR1"     /target/usr/libexec/atomos-app-handler
            check_grep "kill -USR2"     /target/usr/libexec/atomos-app-handler
            check_f /target/etc/xdg/autostart/atomos-app-handler.desktop
            check_grep "Exec=/usr/libexec/atomos-app-handler --start" /target/etc/xdg/autostart/atomos-app-handler.desktop
        fi

        if [ "$FAIL" -ne 0 ]; then
            echo "ERROR: build-fairphone4 final verification failed (see above)." >&2
            exit 1
        fi
        echo "build-fairphone4: final verification OK"
    '

##############################################################################
# Step 6: export boot.img.
#
# Prefer the artifact produced by boot-deploy in Step 1.5 (it knows the
# device's exact mkbootimg invocation, header version, signing
# requirements, etc.). Fall back to a hand-rolled mkbootimg using the
# deviceinfo offsets only when boot-deploy did not deposit a usable
# boot.img.
##############################################################################
echo "=== build-fairphone4: export boot.img ==="
"$ENGINE" run --rm --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target" \
    -v "$EXPORT_DIR:/exportdir" \
    -e DEVICE_DTB="$DEVICE_DTB" \
    -e DEVICE_APPEND_DTB="$DEVICE_APPEND_DTB" \
    -e DEVICE_PAGESIZE="$DEVICE_PAGESIZE" \
    -e DEVICE_BASE="$DEVICE_BASE" \
    -e DEVICE_KOFF="$DEVICE_KOFF" \
    -e DEVICE_ROFF="$DEVICE_ROFF" \
    -e DEVICE_SOFF="$DEVICE_SOFF" \
    -e DEVICE_TOFF="$DEVICE_TOFF" \
    -e DEVICE_KERNEL_CMDLINE="$DEVICE_KERNEL_CMDLINE" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        # ---- boot-deploy output preferred path -------------------------
        # boot-deploy convention: /boot/boot.img-<flavor> for the per-kernel
        # image and /boot/boot.img as a generic copy. When both exist the
        # generic /boot/boot.img is the one to ship.
        for cand in \
            /target/boot/boot.img \
            /target/boot/boot.img-postmarketos-qcom-sm6350 \
            /target/boot/boot.img-pmos; do
            if [ -f "$cand" ]; then
                echo "build-fairphone4: using boot-deploy artifact: $cand"
                cp -f "$cand" /exportdir/boot.img
                ls -la /exportdir/boot.img
                exit 0
            fi
        done
        boot_img_glob="$(ls /target/boot/boot.img* 2>/dev/null | head -n 1 || true)"
        if [ -n "$boot_img_glob" ] && [ -f "$boot_img_glob" ]; then
            echo "build-fairphone4: using boot-deploy artifact (glob): $boot_img_glob"
            cp -f "$boot_img_glob" /exportdir/boot.img
            ls -la /exportdir/boot.img
            exit 0
        fi

        echo "build-fairphone4: no boot-deploy boot.img found; falling back to manual mkbootimg." >&2

        # ---- manual mkbootimg fallback ---------------------------------
        # Locate the kernel image. linux-postmarketos-qcom-sm6350 installs
        # to /boot/vmlinuz-postmarketos-qcom-sm6350 (Alpine convention).
        KERNEL=""
        for k in /target/boot/vmlinuz-postmarketos-qcom-sm6350 \
                 /target/boot/vmlinuz-pmos \
                 /target/boot/vmlinuz; do
            if [ -f "$k" ]; then KERNEL="$k"; break; fi
        done
        if [ -z "$KERNEL" ]; then
            KERNEL="$(ls /target/boot/vmlinuz* 2>/dev/null | head -n 1 || true)"
        fi
        if [ -z "$KERNEL" ] || [ ! -f "$KERNEL" ]; then
            echo "ERROR: no kernel image under /target/boot/" >&2
            ls -la /target/boot/ >&2 || true
            exit 1
        fi
        echo "build-fairphone4: kernel: $KERNEL"

        # Locate the initramfs (postmarketos-mkinitfs writes
        # initramfs-postmarketos-qcom-sm6350 in /boot).
        INITRAMFS=""
        for r in /target/boot/initramfs-postmarketos-qcom-sm6350 \
                 /target/boot/initramfs-pmos \
                 /target/boot/initramfs; do
            if [ -f "$r" ]; then INITRAMFS="$r"; break; fi
        done
        if [ -z "$INITRAMFS" ]; then
            INITRAMFS="$(ls /target/boot/initramfs* 2>/dev/null | head -n 1 || true)"
        fi
        if [ -z "$INITRAMFS" ] || [ ! -f "$INITRAMFS" ]; then
            # Last resort: regenerate via postmarketos-mkinitfs in chroot.
            apk add --no-interactive postmarketos-mkinitfs >/dev/null 2>&1 || true
            chroot /target /sbin/mkinitfs >/dev/null 2>&1 || true
            for r in /target/boot/initramfs-postmarketos-qcom-sm6350 \
                     /target/boot/initramfs-pmos \
                     /target/boot/initramfs; do
                if [ -f "$r" ]; then INITRAMFS="$r"; break; fi
            done
        fi
        if [ -z "$INITRAMFS" ] || [ ! -f "$INITRAMFS" ]; then
            echo "ERROR: no initramfs under /target/boot/" >&2
            ls -la /target/boot/ >&2 || true
            exit 1
        fi
        echo "build-fairphone4: initramfs: $INITRAMFS"

        # Locate DTB. linux-postmarketos-qcom-sm6350 installs DTBs to
        # /usr/share/dtb/<deviceinfo_dtb>.dtb (the .dtb suffix is added
        # by the kernel apk on Alpine).
        DTB_PATH="/target/usr/share/dtb/${DEVICE_DTB}.dtb"
        if [ ! -f "$DTB_PATH" ]; then
            for cand in \
                "/target/boot/dtbs/${DEVICE_DTB}.dtb" \
                "/target/boot/dtbs-postmarketos-qcom-sm6350/${DEVICE_DTB}.dtb" \
                "/target/lib/firmware/dtbs/${DEVICE_DTB}.dtb"; do
                if [ -f "$cand" ]; then DTB_PATH="$cand"; break; fi
            done
        fi
        if [ ! -f "$DTB_PATH" ]; then
            echo "ERROR: DTB not found for ${DEVICE_DTB} (.dtb)" >&2
            find /target -name "*.dtb" -path "*sm7225-fairphone*" 2>/dev/null | sed "s|^|  candidate: |" >&2 || true
            exit 1
        fi
        echo "build-fairphone4: dtb: $DTB_PATH"

        # If deviceinfo says append-dtb, concatenate kernel+DTB into a
        # single image and feed that to mkbootimg. Otherwise pass the DTB
        # via --dt (mkbootimg-osm0sis).
        WORK=/tmp/atomos-bootimg
        mkdir -p "$WORK"
        cp "$KERNEL" "$WORK/kernel"
        if [ "$DEVICE_APPEND_DTB" = "true" ]; then
            cat "$DTB_PATH" >> "$WORK/kernel"
            DTARG=""
        else
            cp "$DTB_PATH" "$WORK/dtb"
            DTARG="--dt $WORK/dtb"
        fi
        cp "$INITRAMFS" "$WORK/initramfs"

        # mkbootimg-osm0sis flags. Keep --header_version 0 (FP4 uses the
        # legacy boot.img header, which is what deviceinfo offsets above
        # describe).
        # shellcheck disable=SC2086
        mkbootimg \
            --kernel "$WORK/kernel" \
            --ramdisk "$WORK/initramfs" \
            --base "$DEVICE_BASE" \
            --kernel_offset "$DEVICE_KOFF" \
            --ramdisk_offset "$DEVICE_ROFF" \
            --second_offset "$DEVICE_SOFF" \
            --tags_offset "$DEVICE_TOFF" \
            --pagesize "$DEVICE_PAGESIZE" \
            --cmdline "$DEVICE_KERNEL_CMDLINE" \
            $DTARG \
            --output /exportdir/boot.img
        ls -la /exportdir/boot.img
    '

##############################################################################
# Step 6.5: pre-pack assertion. Verify the rootfs we are ABOUT to rsync
# into the sparse image still has everything greetd needs at boot.
#
# Step 5 already verified state right after AtomOS overlays applied, but
# nothing between Step 5 and Step 7 should mutate /etc/passwd or the
# runlevel symlinks. If this assertion ever fails, something silently
# regressed the rootfs after final-verify -- catch it here instead of
# shipping a broken sparse image and watching the device boot loop.
##############################################################################
echo "=== build-fairphone4: pre-pack rootfs assertion ==="
"$ENGINE" run --rm --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target:ro" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        FAIL=0
        echo "pre-pack: /etc/passwd greetd row:"
        if grep "^greetd:" /target/etc/passwd; then
            :
        else
            echo "  FAIL: greetd not found in /target/etc/passwd" >&2
            FAIL=1
        fi
        echo "pre-pack: /etc/group greetd row:"
        if grep "^greetd:" /target/etc/group; then
            :
        else
            echo "  FAIL: greetd group not found in /target/etc/group" >&2
            FAIL=1
        fi
        echo "pre-pack: runlevel default symlinks (greetd / seatd / elogind):"
        for svc in greetd seatd elogind; do
            target=/target/etc/runlevels/default/$svc
            if [ -L "$target" ]; then
                echo "  ok   $svc -> $(readlink "$target")"
            elif [ -e "$target" ]; then
                echo "  ok   $svc (regular file present)"
            else
                echo "  FAIL $svc missing under /etc/runlevels/default/" >&2
                FAIL=1
            fi
        done
        if [ "$FAIL" -ne 0 ]; then
            echo "FATAL: pre-pack rootfs assertion failed; refusing to build a broken sparse image." >&2
            echo "       Listing /target/etc/runlevels/default/ for diagnostics:" >&2
            ls -la /target/etc/runlevels/default/ >&2 || true
            exit 14
        fi
        echo "pre-pack: rootfs ready for packing."
    '

##############################################################################
# Step 7: pack rootfs into sparse fairphone-fp4.img (ext4 + img2simg).
##############################################################################
echo "=== build-fairphone4: pack rootfs into sparse image ==="
"$ENGINE" run --rm --privileged --platform "linux/arm64" \
    -v "$ROOTFS_VOLUME:/target:ro" \
    -v "$EXPORT_DIR:/exportdir" \
    -e PROFILE_NAME="$PROFILE_NAME" \
    -e ATOMOS_FP4_ROOTFS_SIZE_MB="${ATOMOS_FP4_ROOTFS_SIZE_MB:-}" \
    -e DEVICE_FLASH_SPARSE="$DEVICE_FLASH_SPARSE" \
    "$ALPINE_IMAGE" /bin/sh -eu -c '
        # Intentionally NOT installing GNU coreutils here. Alpines edge
        # ships coreutils built against a newer musl symbol set than the
        # alpine:edge container image typically carries (the GNU rm fails
        # at load time with "Error relocating /bin/rm: renameat2: symbol
        # not found" when musl is older than 1.2.3+). Busybox supports
        # every option this script uses (truncate -s NM, du -sk, rm -f,
        # ls -la), so coreutils is unnecessary for the packing stage. The
        # rootfs itself still has GNU coreutils because boot-deploy needs
        # it in the chroot; that install path is unaffected.
        apk add --no-interactive e2fsprogs util-linux mount rsync android-tools >/dev/null
        RAW=/exportdir/${PROFILE_NAME}.raw.img
        SPARSE=/exportdir/${PROFILE_NAME}.img
        rm -f "$RAW" "$SPARSE"

        if [ -n "${ATOMOS_FP4_ROOTFS_SIZE_MB:-}" ]; then
            SIZE_MB="$ATOMOS_FP4_ROOTFS_SIZE_MB"
        else
            # Used + 256 MiB headroom (free space for first-boot + apk add).
            USED_KB="$(du -sk /target | cut -f1)"
            SIZE_MB=$(( (USED_KB / 1024) + 256 ))
            # Round up to nearest 64 MiB.
            REM=$(( SIZE_MB % 64 ))
            if [ "$REM" -ne 0 ]; then SIZE_MB=$(( SIZE_MB + 64 - REM )); fi
        fi
        echo "build-fairphone4: rootfs raw image size = ${SIZE_MB} MiB"

        # Allocate sparse file and create ext4 inside it.
        truncate -s "${SIZE_MB}M" "$RAW"
        # Filesystem label MUST be "pmOS_root". The postmarketos-initramfs
        # init script (pmaports/main/postmarketos-initramfs/init_functions.sh
        # find_root_partition) locates the rootfs via:
        #   PMOS_ROOT="$(find_partition "$root_uuid" "$root_path" "pmOS_root" ...)"
        # which falls back to `blkid --label pmOS_root`. With any other
        # label, the device boots into "Waiting for root partition..."
        # forever because blkid returns no match.
        mkfs.ext4 -F -L pmOS_root "$RAW"

        mkdir -p /mnt/root
        mount -o loop "$RAW" /mnt/root
        rsync -aHAX --delete --numeric-ids /target/ /mnt/root/
        sync
        umount /mnt/root

        if [ "${DEVICE_FLASH_SPARSE:-true}" = "true" ]; then
            echo "build-fairphone4: converting raw image to sparse via img2simg"
            img2simg "$RAW" "$SPARSE"
            rm -f "$RAW"
        else
            mv "$RAW" "$SPARSE"
        fi
        ls -la "$SPARSE"
    '

# Best-effort export ownership normalize (matches build-qemu).
if [ "${ATOMOS_SKIP_EXPORT_CHOWN:-0}" != "1" ]; then
    if ! "$ENGINE" run --rm \
        -v "$EXPORT_DIR:/export" \
        "$ALPINE_IMAGE" /bin/sh -eu -c "chown -R $HOST_UID:$HOST_GID /export" >/dev/null 2>&1; then
        echo "Note: skipped export ownership adjustment (expected on some rootless runtimes)."
    fi
fi

echo ""
echo "Build complete:"
echo "  $BOOT_IMG_PATH"
echo "  $ROOTFS_IMG_PATH"
echo ""
echo "Flash with fastboot (device in bootloader):"
echo "  fastboot flash boot     $BOOT_IMG_PATH"
echo "  fastboot flash userdata $ROOTFS_IMG_PATH"
